#ifndef LAUNCHER_THEME_H
#define LAUNCHER_THEME_H

#define LAUNCHER_COLOR_TEXT      0xFFFF
#define LAUNCHER_COLOR_HIGHLIGHT 0x83FF

#define LAUNCHER_TITLE_Y         18
#define LAUNCHER_HINT_UPPER_Y    180
#define LAUNCHER_HINT_BOTTOM_Y   194

#define LAUNCHER_MAIN_TITLE_X    92
#define LAUNCHER_MAIN_ITEM0_X    74
#define LAUNCHER_MAIN_ITEM0_Y    82
#define LAUNCHER_MAIN_ITEM1_X    74
#define LAUNCHER_MAIN_ITEM1_Y    98
#define LAUNCHER_MAIN_ITEM2_X    92
#define LAUNCHER_MAIN_ITEM2_Y    114
#define LAUNCHER_MAIN_INFO_X     50
#define LAUNCHER_MAIN_INFO_Y     146
#define LAUNCHER_MAIN_VALUE_X    26
#define LAUNCHER_MAIN_VALUE_Y    160

#define LAUNCHER_BROWSER_TITLE_X 74
#define LAUNCHER_BROWSER_PATH_X  8
#define LAUNCHER_BROWSER_PATH_Y  34
#define LAUNCHER_BROWSER_LIST_X  8
#define LAUNCHER_BROWSER_LIST_Y  54
#define LAUNCHER_BROWSER_STEP_Y  14
#define LAUNCHER_BROWSER_ROWS    8

#define LAUNCHER_OPT_TITLE_X     94
#define LAUNCHER_OPT_INFO_X      68
#define LAUNCHER_OPT_INFO_Y      92
#define LAUNCHER_OPT_BACK_X      114
#define LAUNCHER_OPT_BACK_Y      116

#endif
