#ifndef SELECT_MENU_THEME_H
#define SELECT_MENU_THEME_H

#define SELECT_MENU_COLOR_TEXT      0xFFFF
#define SELECT_MENU_COLOR_HIGHLIGHT 0x83FF

#define SELECT_MENU_TITLE_Y         18
#define SELECT_MENU_HINT_BOTTOM_Y   194
#define SELECT_MENU_HINT_UPPER_Y    180

#define SELECT_MENU_MAIN_RESUME_X   104
#define SELECT_MENU_MAIN_RESUME_Y   92
#define SELECT_MENU_MAIN_VIDEO_X    116
#define SELECT_MENU_MAIN_VIDEO_Y    110

#define SELECT_MENU_VIDEO_TITLE_X   110
#define SELECT_MENU_VIDEO_ITEM0_X   62
#define SELECT_MENU_VIDEO_ITEM0_Y   88
#define SELECT_MENU_VIDEO_ITEM1_X   80
#define SELECT_MENU_VIDEO_ITEM1_Y   106
#define SELECT_MENU_VIDEO_ITEM2_X   116
#define SELECT_MENU_VIDEO_ITEM2_Y   124

#define SELECT_MENU_DISPLAY_TITLE_X 74
#define SELECT_MENU_DISPLAY_INFO_X  80
#define SELECT_MENU_DISPLAY_INFO_Y  74
#define SELECT_MENU_DISPLAY_X_X     104
#define SELECT_MENU_DISPLAY_X_Y     94
#define SELECT_MENU_DISPLAY_Y_X     104
#define SELECT_MENU_DISPLAY_Y_Y     108
#define SELECT_MENU_DISPLAY_HINT_X  47
#define SELECT_MENU_DISPLAY_HINT_Y  130

#define SELECT_MENU_ASPECT_TITLE_X  86
#define SELECT_MENU_ASPECT_ITEM0_X  118
#define SELECT_MENU_ASPECT_ITEM0_Y  74
#define SELECT_MENU_ASPECT_ITEM1_X  114
#define SELECT_MENU_ASPECT_ITEM1_Y  88
#define SELECT_MENU_ASPECT_ITEM2_X  74
#define SELECT_MENU_ASPECT_ITEM2_Y  102
#define SELECT_MENU_ASPECT_ITEM3_X  68
#define SELECT_MENU_ASPECT_ITEM3_Y  116
#define SELECT_MENU_ASPECT_ITEM4_X  114
#define SELECT_MENU_ASPECT_ITEM4_Y  130
#define SELECT_MENU_ASPECT_HINT_X   38
#define SELECT_MENU_ASPECT_HINT_Y   170

#endif
