#ifndef PS2_AUDIO_INTERNAL_H
#define PS2_AUDIO_INTERNAL_H

#include "ps2_audio.h"

#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include "ps2_audio_backend.h"

#define QUIET_PS2AUDIO_LOGS 1
#if QUIET_PS2AUDIO_LOGS
#define PS2AUDIO_LOG(...) ((void)0)
#else
#define PS2AUDIO_LOG(...) printf(__VA_ARGS__)
#endif

#define PS2_AUDIO_RATE              CORE_AUDIO_RATE
#define CORE_AUDIO_RATE             32040
#define PS2_AUDIO_CHANNELS          2
#define PS2_AUDIO_BYTES_PER_SAMPLE  2
#define PS2_AUDIO_FRAME_BYTES       (PS2_AUDIO_CHANNELS * PS2_AUDIO_BYTES_PER_SAMPLE)
#define PS2_AUDIO_BACKEND_VOLUME    0x3fff
#define PS2_AUDIO_FADE_STEPS       6
#define PS2_AUDIO_FADE_DELAY_US    750
#define AUDIO_UNDERRUN_HYSTERESIS_LOOPS  3

#define SOUND_BLOCK_COUNT 8
#define SOUND_BUFFER_CHUNK          1024
#define SOUND_TOTAL_FRAMES          (SOUND_BLOCK_COUNT * SOUND_BUFFER_CHUNK)
#define SOUND_TOTAL_BYTES           (SOUND_TOTAL_FRAMES * PS2_AUDIO_FRAME_BYTES)

#define BACKEND_FEED_FRAMES         512
#define BACKEND_FEED_BYTES          (BACKEND_FEED_FRAMES * PS2_AUDIO_FRAME_BYTES)
#define BACKEND_QUEUE_TARGET_FRAMES (BACKEND_FEED_FRAMES * 4)
#define BACKEND_QUEUE_TARGET_BYTES  (BACKEND_QUEUE_TARGET_FRAMES * PS2_AUDIO_FRAME_BYTES)
#define BACKEND_RESUME_UNMUTE_FRAMES (BACKEND_FEED_FRAMES * 4)
#define BACKEND_REAL_TARGET_FRAMES  (BACKEND_FEED_FRAMES * 2)
#define BACKEND_REAL_TARGET_BYTES   (BACKEND_REAL_TARGET_FRAMES * PS2_AUDIO_FRAME_BYTES)

#define SOUND_THREAD_PRIO           96
#define SOUND_THREAD_STACK          0x2000

#endif
